### ISSUE TITLE
Overlapping events with priority

### ISSUE THREAD

**Issue by alexg-k** [rolfn/kalenderRN#3]
First of all thank you for the effort you put into this promising calendar library!

I struggle with multiple events that happen on the same day. The calendar shows only one of the events, but I can not influence which one. Also sometimes the text of one event is displayed but the background color of another event is shown. This is very confusing..

**Comment by rolfn** [comment]
You should give me a complete example (.tex) to show the issues. Unfortunately I have not much time for corrections.

**Comment by alexg-k** [comment]
There you go:

**calendar.tex**
```
\listfiles

\documentclass{tikz-kalender}
\usepackage{xcolor}

\definecolor{hsu-red}{RGB}{165,0,52}
\definecolor{hsu-grey}{RGB}{140,130,121}

% all options:
\setup{%
 	,lang=german% language for day names and month names; default: english
    	,paper=a4% papersize understandable by the geometry package; default: a4
    	,year=2018% base of the calender calculation
    	,yearFont={\itshape}% additional font definition
    	,titleFont={\fontsize{1.2em}{1.2em}}% ~120% of default
    	,titleColor=hsu-red
 	,monthBGcolor=hsu-red% additional font definition
 	,saturdayColor=hsu-grey!50!white% additional font definitionr
	,sundayColor=hsu-grey% additional font definition
	,showweeknumbers% default: false
	,events={events/birthdays, events/appointments}% events and periods
	,print=false% printer-friendly orientation (double-side printing)
}

\begin{document}
 	\makeKalender
\end{document}
```
**appointments.events**
```
\event*{2018-01-05}{Dentist}[color=yellow!15]
\endinput
```

**birthdays.events**
```
\event{\year-01-05}{Mr. Smith}
\endinput
```

What I get is this: 
[calendar_2018.pdf](https://github.com/rolfn/kalenderRN/files/1599689/calendar_2018.pdf)

**Comment by rolfn** [comment]
I can tell you the following. First of all: The current version of `tikz-kalender` can only show one event for the same day. The first (!) event in every event lists wins. Color definitions are only effective for the star form of the macro `\event`. If you want colored entries use for both the star form and put the more important entry at the first place of the events key (`\setup`). I can't offer a better solution at this time.

**Comment by 0rph3us** [comment]
Is it possible to concatenate all events names in the list?
