### ISSUE TITLE
Using \year in an event command results in an error

### ISSUE THREAD

**Issue by UweZiegenhagen** [rolfn/kalenderRN#5]
Example was taken from the documentation, brings an error.

\documentclass{tikz-kalender}
\setup{%
lang=german,
year=2020,
title={Urlaub},
xcoloroptions={x11names},
titleColor=cyan,
eventColor=brown,
periodColor=lime,
monthBGcolor=red,
monthColor=Purple0,
workdayColor=yellow,
saturdayColor=magenta,
sundayColor=orange}

\begin{document}
\event{\year-10-09}{John Lennon (1940)}
\makeKalender
\end{document}

! Missing \endcsname inserted.
<to be read again>
\year
<argument> event@\year
-10-09
\@ifundefined #1->\ifcsname #1
\endcsname \@ifundefin@d@i \else \@ifundefin@d...
\RN@event@ii ...hS }{}\fi \@ifundefined {event@#1}
{\expandafter \protected@x...
<to be read again>
\event
l.21 \event
{2020-10-03}{Tag d. dt. Einheit}
?

**Comment by rolfn** [comment]
The event macro is only allowed inside of an external file (.events). See `tikz-kalender-example1.tex` as an example.
