### ISSUE TITLE
One sided calender

### ISSUE THREAD

**Issue by eglaar** [rolfn/kalenderRN#6]
Hello,
thank you for your work. 
I tried to adopt you approch and create a calendar which is only on one sheet.
Can you give me a nudge in the right direction?
[tikz-kalender-example1.pdf](https://github.com/rolfn/kalenderRN/files/4025667/tikz-kalender-example1.pdf)

**Comment by rolfn** [comment]
I don't have the time to implement a one-side version. But you can do something like the following:
```latex
% one-side.tex
\documentclass[paper=a3]{scrartcl}
\usepackage{pdfpages}
\begin{document}
  \includepdf[pages=-,nup=1x2]{tikz-kalender-example1.pdf}
\end{document}
```
